replicaCount: 2

image:
  repository: shivawmm1810/quote-api-app
  tag: "4fd8da584fea9ba9591e65b698e266f2a64eaa35"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

containerPort: 3000

environment: development

ingress:
  enabled: true
  className: nginx
  host: quote-api.local

resources:
  limits:
    cpu: 200m
    memory: 256Mi

  requests:
    cpu: 100m
    memory: 128Mi