apiVersion: v1
kind: Service

metadata:
  name: {{ include "quote-api-app.fullname" . }}
  namespace: helm-argocd-demo

spec:
  type: {{ .Values.service.type }}

  selector:
    app: quote-api-app

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}